import { ArrowUpRight, MapPin, Mail, MessageCircle, Info, ShieldCheck, Clock } from 'lucide-react'
import { profile, contactAssurances } from '../data/content'
import { getWhatsAppUrl } from '../data/contact'

const assuranceIcons = { ShieldCheck, Clock, MapPin }

export default function Contact() {
  const whatsapp = getWhatsAppUrl()
  return <section id="contato" className="contact section" aria-labelledby="contact-title"><div className="container contact-grid"><div className="contact-copy"><p className="eyebrow">VAMOS CONVERSAR</p><h2 id="contact-title">Vamos criar o site<br />da sua <span>empresa?</span></h2><p>Conte sobre seu negócio e o que você precisa. Vamos conversar sobre uma solução adequada para sua empresa.</p><div className="contact-details"><div><span className="contact-icon"><MapPin size={21} /></span><div><span>Atendimento próximo</span><p>{profile.location}</p></div></div>{whatsapp && <a href={whatsapp} target="_blank" rel="noreferrer"><span className="contact-icon"><MessageCircle size={21} /></span><span>Conversar pelo WhatsApp <ArrowUpRight size={16} /></span></a>}{profile.email && <a href={`mailto:${profile.email}`}><span className="contact-icon"><Mail size={21} /></span><span>{profile.email}</span></a>}</div><div className="contact-signature">Eduardo Henrique<span>DESIGN COM INTENÇÃO. CÓDIGO COM CUIDADO.</span></div></div><form className="contact-form" aria-label="Formulário de orçamento demonstrativo" aria-describedby="demo-notice" onSubmit={event => event.preventDefault()}><div id="demo-notice" className="demo-notice"><Info size={19} /><p><strong>Formulário de demonstração</strong>O envio não está disponível nesta versão. Nenhum dado será enviado ou salvo.</p></div><div className="form-row"><label htmlFor="name">Nome<input id="name" name="name" type="text" autoComplete="off" placeholder="Como você se chama?" /></label><label htmlFor="company">Empresa<input id="company" name="company" type="text" autoComplete="off" placeholder="Nome da sua empresa" /></label></div><label htmlFor="reply">E-mail ou WhatsApp para retorno<input id="reply" name="reply" type="text" autoComplete="off" placeholder="Seu contato de preferência" /></label><label htmlFor="site-type">Tipo de site<select id="site-type" name="siteType" defaultValue=""><option value="" disabled>Selecione uma opção</option><option>Landing page</option><option>Site institucional</option><option>Manutenção e atualizações</option><option>Automação e integrações</option><option>Ainda não sei</option></select></label><label htmlFor="message">Mensagem<textarea id="message" name="message" rows="3" placeholder="Conte um pouco sobre seu negócio e sua ideia…" /></label><button className="button" type="submit" disabled>Envio indisponível nesta demonstração <ArrowUpRight size={17} /></button></form><ul className="contact-assurances" aria-label="Compromissos do atendimento">{contactAssurances.map(({ icon, text }) => { const Icon = assuranceIcons[icon]; return <li key={text}><Icon size={17} strokeWidth={1.5} aria-hidden="true" /><span>{text}</span></li> })}</ul></div></section>
}
